name: Auto-merge Dependabot PRs

on:
  pull_request:
    types: [opened, reopened, synchronize, ready_for_review]

jobs:
  auto-merge:
    # Only run on dependabot PRs
    if: github.actor == 'dependabot[bot]' && github.event.pull_request.draft == false
    runs-on: ubuntu-latest
    
    permissions:
      contents: write
      pull-requests: write
    
    steps:
      - name: Enable auto-merge for Dependabot PRs
        run: |
          echo "Enabling auto-merge for dependabot PR #${{ github.event.pull_request.number }}"
          gh pr merge ${{ github.event.pull_request.number }} --auto --squash --repo ${{ github.repository }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          
      - name: Add auto-merge comment
        run: |
          gh pr comment ${{ github.event.pull_request.number }} --body "🤖 Auto-merge has been enabled for this dependabot PR. It will merge automatically once all required status checks pass." --repo ${{ github.repository }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}